k apply -n cre-system -f - << EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  config.yaml: |
    triggers:
      - name: sync-operation-succeeded
        condition: app.status.operationState.phase in ['Succeeded']
        template: sync-operation-status-change

    templates:
      - name: sync-operation-status-change
        webhook:
          devhose:
            method: POST
            path: /test
            body: |
              {
                {{if eq .app.status.operationState.phase "Succeeded"}} "state": "success"{{end}}
                ,
                "clusterName": "ariatest",
                "name": "{{.app.metadata.name}}",
                "eventType": "namespace-provisioned",
                "scope": "namespace"
              }
EOF
