k apply -n cre-system -f - << EOF
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifiers.yaml: |
    webhook:
    - name: devhose
      url: http://devhose.mpi-internal.com/devhose
      headers: 
      - name: DevHose-AuthContext
        value: eyJ0eXBlIjoic2NoaXAifQ==
      - name: Authorization
        value: token eyJ0eXBlIjoic2NoaXAifQ==

type: Opaque
EOF